"""Sample movie catalog for development and demos.

Facts about films are public information. The `providers` field is sample
data for the MVP demo; the real implementation will read it from TMDB's
watch-providers endpoint (attribution required: Data from JustWatch via TMDB).
"""

from __future__ import annotations

from .models import Movie

CATALOG: list[Movie] = [
    Movie(
        id="m_toy_story",
        title="Toy Story",
        year=1995,
        runtime_min=81,
        genres=["Animation", "Family", "Comedy"],
        tags=["kid-safe", "heartwarming", "adventure", "classic"],
        content_rating="G",
        providers=["Disney+"],
        logline="Toys come to life when their owner is away.",
    ),
    Movie(
        id="m_duck_soup",
        title="Duck Soup",
        year=1933,
        runtime_min=68,
        genres=["Comedy"],
        tags=["classic", "silly", "quotable"],
        content_rating="G",
        providers=["Rent/Buy"],
        logline="A tiny nation is led into absurd war by a scheming ruler.",
    ),
    Movie(
        id="m_coco",
        title="Coco",
        year=2017,
        runtime_min=105,
        genres=["Animation", "Family", "Music"],
        tags=["kid-safe", "heartwarming", "emotional", "music"],
        content_rating="PG",
        providers=["Disney+"],
        logline="A boy visits the Land of the Dead to uncover his family's history.",
    ),
    Movie(
        id="m_paddington2",
        title="Paddington 2",
        year=2017,
        runtime_min=103,
        genres=["Family", "Comedy", "Adventure"],
        tags=["kid-safe", "heartwarming", "funny", "cozy"],
        content_rating="PG",
        providers=["Netflix"],
        logline="A polite bear hunts the thief who stole his aunt's gift.",
    ),
    Movie(
        id="m_home_alone",
        title="Home Alone",
        year=1990,
        runtime_min=103,
        genres=["Comedy", "Family"],
        tags=["classic", "funny", "holiday", "slapstick"],
        content_rating="PG",
        providers=["Disney+"],
        logline="A boy left behind defends his house from burglars.",
    ),
    Movie(
        id="m_spiderverse",
        title="Spider-Man: Into the Spider-Verse",
        year=2018,
        runtime_min=117,
        genres=["Animation", "Action", "Adventure"],
        tags=["stylish", "action", "kid-safe", "music"],
        content_rating="PG",
        providers=["Netflix"],
        logline="A Brooklyn teen becomes Spider-Man alongside heroes from other universes.",
    ),
    Movie(
        id="m_grand_budapest",
        title="The Grand Budapest Hotel",
        year=2014,
        runtime_min=99,
        genres=["Comedy", "Drama"],
        tags=["stylish", "quirky", "funny"],
        content_rating="R",
        providers=["Max"],
        logline="A legendary concierge and his protege chase a stolen painting.",
    ),
    Movie(
        id="m_knives_out",
        title="Knives Out",
        year=2019,
        runtime_min=130,
        genres=["Mystery", "Comedy", "Drama"],
        tags=["whodunit", "twisty", "funny"],
        content_rating="PG-13",
        providers=["Netflix"],
        logline="A detective untangles a wealthy novelist's chaotic family.",
    ),
    Movie(
        id="m_spirited_away",
        title="Spirited Away",
        year=2001,
        runtime_min=125,
        genres=["Animation", "Fantasy", "Adventure"],
        tags=["magical", "emotional", "artistic", "kid-safe"],
        content_rating="PG",
        providers=["Max"],
        logline="A girl works in a bathhouse for spirits to save her parents.",
    ),
    Movie(
        id="m_back_to_future",
        title="Back to the Future",
        year=1985,
        runtime_min=116,
        genres=["Adventure", "Sci-Fi", "Comedy"],
        tags=["classic", "fun", "time-travel"],
        content_rating="PG",
        providers=["Rent/Buy"],
        logline="A teen travels 30 years back and jeopardizes his own birth.",
    ),
    Movie(
        id="m_incredibles",
        title="The Incredibles",
        year=2004,
        runtime_min=115,
        genres=["Animation", "Action", "Family"],
        tags=["kid-safe", "action", "funny", "superhero"],
        content_rating="PG",
        providers=["Disney+"],
        logline="A family of retired superheroes must save the world again.",
    ),
    Movie(
        id="m_ratatouille",
        title="Ratatouille",
        year=2007,
        runtime_min=111,
        genres=["Animation", "Family", "Comedy"],
        tags=["kid-safe", "cozy", "food", "heartwarming"],
        content_rating="G",
        providers=["Disney+"],
        logline="A rat with a refined palate secretly becomes a Paris chef.",
    ),
    Movie(
        id="m_forrest_gump",
        title="Forrest Gump",
        year=1994,
        runtime_min=142,
        genres=["Drama", "Romance"],
        tags=["classic", "emotional", "heartwarming"],
        content_rating="PG-13",
        providers=["Netflix"],
        logline="A kind-hearted man stumbles through decades of American history.",
    ),
    Movie(
        id="m_interstellar",
        title="Interstellar",
        year=2014,
        runtime_min=169,
        genres=["Sci-Fi", "Drama", "Adventure"],
        tags=["epic", "emotional", "space", "serious"],
        content_rating="PG-13",
        providers=["Paramount+"],
        logline="A farmer leads a mission through a wormhole to save humanity.",
    ),
    Movie(
        id="m_jumanji_wtjt",
        title="Jumanji: Welcome to the Jungle",
        year=2017,
        runtime_min=119,
        genres=["Action", "Adventure", "Comedy"],
        tags=["funny", "action", "teen"],
        content_rating="PG-13",
        providers=["Netflix"],
        logline="Four teens are pulled into a video game as their avatars.",
    ),
    Movie(
        id="m_pans_labyrinth",
        title="Pan's Labyrinth",
        year=2006,
        runtime_min=118,
        genres=["Fantasy", "Drama"],
        tags=["dark", "scary", "artistic", "serious"],
        content_rating="R",
        providers=["Max"],
        logline="A girl in postwar Spain discovers a labyrinth of dark fae.",
    ),
]
